---
title: "CombiningDataframes"
author: "Emily Wefelmeyer"
date: "November 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries
```{r}
if (!require('RCurl')) install.packages('RCurl', quiet=TRUE)
require(Rcurl)

if (!require('readxl')) install.packages('readxl', quiet=TRUE)
library(readxl)

if (!require('dplyr')) install.packages('dplyr', quiet=TRUE)
library(dplyr)

if (!require('Hmisc')) install.packages('Hmisc', quiet=TRUE)
library(Hmisc)

if (!require("stringr")) install.packages("stringr", quiet = TRUE)
library(stringr)

if (!require("lubridate")) install.packages("lubridate", quiet = TRUE)
library(lubridate)
```

##Combine to one data frame
###Data frames redefined by actual date/time data using
```{r}

DateTime <- as.data.frame(seq(ISOdatetime(1983, 8, 10, 0, 0, 0, tz = "" ), 
                ISOdatetime(2018, 10, 1, 0, 0, 0, tz = ""),
                by = "4 hours"))
colnames(DateTime) = "DateTime"

StationID <- unique(chemistry2$StationID)
StationID <- as.numeric(StationID)
nStations = as.numeric(length(StationID))

micro2 <- merge(DateTime, 
                  micro, 
                  by.x = "DateTime", 
                  by.y = "DateTime", 
                  all.x = TRUE)

chemistry3 <- merge(DateTime,
                    chemistry2,
                    by.x = "DateTime",
                    by.y = "DateTime")
```

###Combine chemistry, fish count & macro count data
```{r}
#Create initial data frame from varous pieces
chem <- subset(chemistry3, StationID == StationID[1])
fish <- subset(fishCounts2, StationID == StationID[1])
macro <- subset(macroCounts2, Station_ID == StationID[1])

#Combine fish & macro counts
temp <- merge(fish,
              macro,
              by = "DateTime",
              all = TRUE)

#Clean to have unified station ID
temp$StationID <- rep(StationID[1], times = nrow(temp))
temp$Station_ID.x <- NULL
temp$Station_ID.y <- NULL

#Add in chemistry
temp <- merge(chem,
              temp,
              by = "DateTime",
              all.x = TRUE,
              all.y = TRUE)

#Clean to have unified station ID
temp$StationID <- rep(StationID[1], times = nrow(temp))
temp$StationID.x <- NULL
temp$StationID.y <- NULL

#Create initial data frame
data <- temp
rm(temp)

#Combine rest of the data frames
for(station in StationID[2:nStations]) {
  chem <- subset(chemistry3, StationID == station)
  fish <- subset(fishCounts2, StationID == station)
  macro <- subset(macroCounts2, StationID == station)
  
  #Combine fish & macro counts
  temp <- merge(fish,
                macro,
                by = "DateTime",
                all = TRUE)
  
  #Clean to have unified station ID
  temp$StationID <- rep(station, times = nrow(temp))
  temp$Station_ID.x <- NULL
  temp$Station_ID.y <- NULL

  #Add chemistry data
  temp <- merge(chem,
                temp,
                by = "DateTime",
                all.x = TRUE,
                all.y = TRUE)
  
  #Clean to have unified station ID
  temp$StationID <- rep(station, times = nrow(temp))
  temp$StationID.x <- NULL
  temp$StationID.y <- NULL

  #Add station's data to the full data set
  ifelse(nrow(temp) > 0, 
    (data[(nrow(data)+1):(nrow(data) + nrow(temp)),] <- temp[1:nrow(temp),]),
    data <- data)
}

#rename data frame
fishMacroCountsWithChem <- data
rm(chem, data, fish, macro, nStations, station, temp)

summary(fishMacroCountsWithChem)
```


##Combine micro df with fish & macro counts df
```{r}
chemFishMacroMicro <- merge(micro2,
                        fishMacroCountsWithChem,
                        by = "DateTime",
                        all = TRUE)
summary(chemFishMacroMicro)
```

##Add attributes
```{r}
allData <- merge(attributes,
                 chemFishMacroMicro,
                 by.x = "Station.ID",
                 by.y = "StationID",
                 all.y = TRUE)

summary(allData)
```

Remove unneed variables
```{r}
rm(DateTime, StationID)
```
