---
title: "DataImport_Final"
author: "Emily Wefelmeyer"
date: "November 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries
```{r}
if (!require('RCurl')) install.packages('RCurl', quiet=TRUE)
require(Rcurl)

if (!require('readxl')) install.packages('readxl', quiet=TRUE)
library(readxl)

if (!require('dplyr')) install.packages('dplyr', quiet=TRUE)
library(dplyr)

if (!require('Hmisc')) install.packages('Hmisc', quiet=TRUE)
library(Hmisc)

if (!require("stringr")) install.packages("stringr", quiet = TRUE)
library(stringr)

if (!require("lubridate")) install.packages("lubridate", quiet = TRUE)
library(lubridate)
```

##Import Excel files from Git
###Function
```{r}
importGitHub <- function(url, skip){
  df <- read.csv(text = getURL(url),
                 skip = skip)
  
  return(df)
}
```

###Chemistry Data 
####Load chemistry data prior to 2018
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/AllPineCreekChemistry.csv"

skip = 1

colNames <- c("StationID",
              "StationName",
              "Date",
              "Time",
              "Parameter",
              "Results",
              "RDL")

chemistry <- importGitHub(url, skip)

colnames(chemistry) <- colNames

rm(skip, url, colNames)

describe(chemistry)
str(chemistry)
```

####Add additional chemistry data from 2018
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/2018PineHU.csv"

skip = 1

colNames <- c("StationID",
              "StationName",
              "Date",
              "Time",
              "Parameter",
              "Results",
              "RDL")

temp <- importGitHub(url, skip)
colnames(temp) <- colNames
rm(colNames, skip, url)

#Combine Chemistry data frames
chemistry <- rbind(chemistry, temp)

chemistry <- unique(chemistry)

rm(temp)
```

####Clean up chemistry data
#####Clean parameters
```{r}
#Change from factors to characters
chemistry$Parameter <- as.character(chemistry$Parameter)

#Remove ","s
chemistry$Parameter <- gsub(",", "", chemistry$Parameter)

#Remove " - Field " from parameter names
chemistry$Parameter <- gsub("- Field", "", chemistry$Parameter)

#Remove "Total " from parameter names
chemistry$Parameter <- gsub("Total", "", chemistry$Parameter)

#Remove "TOT" from parameter names
chemistry$Parameter <- gsub("TOT ", "", chemistry$Parameter)

#Remove "T" from parameter names
chemistry$Parameter <- gsub(" T ", " ", chemistry$Parameter)

#Remove "D" from parameter names
chemistry$Parameter <- gsub(" D ", " ", chemistry$Parameter)

#Remove "Dissolved" from parameter names
chemistry$Parameter <- gsub("Dissolved", "", chemistry$Parameter)

#Remove spaces
chemistry$Parameter <- gsub("  ", " ", chemistry$Parameter)

#Remove "(None)" from pH
chemistry$Parameter <- gsub("\\(None\\)", "", chemistry$Parameter)

#Replace "Specific Con(umho/cm)" with "Specific Conductivity (umho/cm)"
chemistry <- within(chemistry,
                    Parameter[Parameter == "Specific Con (umho/cm)"] <- "Specific Conductivity (umho/cm)")

#Replace "T Org Carbon" with "Carbon"
chemistry$Parameter <- gsub("T Org Carbon", "Carbon", chemistry$Parameter)

#Replace " Oxygen" with "Oxygen"
chemistry$Parameter <- gsub(" Oxygen", "Oxygen", chemistry$Parameter)

#Replace "Organic N" with "Nitrogen"
chemistry$Parameter <- gsub("Organic N", "Nitrogen", chemistry$Parameter)

#Replace "N" with "Nitrogen"
chemistry$Parameter <- gsub(" N ", "Nitrogen", chemistry$Parameter)

#Change "Aluminum (mg/l)" to "Aluminum (ug/l)"
chemistry$Results <- ifelse((chemistry$Parameter == "Aluminum (mg/l)" & 
                               is.numeric(chemistry$Results) == TRUE &  
                               !is.na(chemistry$Results)), 
                            chemistry$Results * 1000,
                            chemistry$Results)

chemistry$RDL <- ifelse((chemistry$Parameter == "Aluminum (mg/l)" & !is.na(chemistry$RDL)), 
                            chemistry$RDL * 1000,
                            chemistry$RDL)

chemistry <- within(chemistry,
                    Parameter[Parameter == "Aluminum (mg/l)"] <- "Aluminum (ug/l)")

#Change "Barium (mg/l)" to "Barium (ug/l)"
chemistry$Results <- ifelse((chemistry$Parameter == "Barium (mg/l)" & 
                               is.numeric(chemistry$Results) == TRUE &  
                               !is.na(chemistry$Results)), 
                            chemistry$Results * 1000,
                            chemistry$Results)
  
chemistry$RDL <- ifelse((chemistry$Parameter == "Barium (mg/l)" & !is.na(chemistry$RDL)), 
                            chemistry$RDL * 1000,
                            chemistry$RDL)

chemistry <- within(chemistry,
                    Parameter[Parameter == "Barium (mg/l)"] <- "Barium (ug/l)")


#Change "Bromide (mg/l)" to "Bromide (ug/l)"
chemistry$Results <- ifelse((chemistry$Parameter == "Bromide (mg/l)" & 
                               is.numeric(chemistry$Results) == TRUE & 
                               !is.na(chemistry$Results)), 
                            chemistry$Results * 1000,
                            chemistry$Results)
  
chemistry$RDL <- ifelse((chemistry$Parameter == "Bromide (mg/l)" & !is.na(chemistry$RDL)), 
                            chemistry$RDL * 1000,
                            chemistry$RDL)

chemistry <- within(chemistry,
                    Parameter[Parameter == "Bromide (mg/l)"] <- "Bromide (ug/l)")


#Change "Iron (mg/l)" to "Iron (ug/l)"
chemistry$Results <- ifelse((chemistry$Parameter == "Iron (mg/l)" & 
                               is.numeric(chemistry$Results) == TRUE & 
                               !is.na(chemistry$Results)), 
                            chemistry$Results * 1000,
                            chemistry$Results)

chemistry$RDL <- ifelse((chemistry$Parameter == "Iron (mg/l)" & !is.na(chemistry$RDL)), 
                            chemistry$RDL * 1000,
                            chemistry$RDL)

  
chemistry <- within(chemistry,
                    Parameter[Parameter == "Iron (mg/l)"] <- "Iron (ug/l)")


#Change "Manganese (mg/l)" to "Manganese (ug/l)"
chemistry$Results <- ifelse((chemistry$Parameter == "Manganese (mg/l)" & 
                               is.numeric(chemistry$Results) == TRUE & 
                               !is.na(chemistry$Results)), 
                            chemistry$Results * 1000,
                            chemistry$Results)

chemistry$RDL <- ifelse((chemistry$Parameter == "Manganese (mg/l)" & !is.na(chemistry$RDL)), 
                            chemistry$RDL * 1000,
                            chemistry$RDL)
    
chemistry <- within(chemistry,
                    Parameter[Parameter == "Manganese (mg/l)"] <- "Manganese (ug/l)")

chemistry$Parameter <- as.factor(chemistry$Parameter)
```

#####Clean Results
```{r}
#Store the parameters & levels of those below quantification limit
chemistry$Results <- ifelse(chemistry$Results ==
                              "Present Below Quantification Limit", 
                            ifelse(is.na(chemistry$RDL),
                                   chemistry$Results,
                                   paste("<", chemistry$RDL, sep = "")),
                            chemistry$Results)

chemistry$Results <- ifelse(is.na(chemistry$Results),
                            ifelse(is.na(chemistry$RDL),
                                   chemistry$Results,
                                   paste("<", chemistry$RDL, sep = "")),
                            chemistry$Results)

chemistry$RDL = NULL  #Drop RDL since placed in results
```

#####Fix date/time stamp
```{r}
#Fix DateTime Stamp from import
temp = t(as.data.frame(strsplit(as.character(chemistry$Time),' ')))
rownames(temp)=NULL
chemistry$Time <- temp
rm(temp)

chemistry$Date <- as.Date(chemistry$Date, format = "%m/%d/%Y")


chemistry$DateTime <- as.POSIXct(paste(chemistry$Date,
                                       chemistry$Time), 
                                 format = "%Y-%m-%d %H:%M")

#Remove redundent variables
chemistry$Date <- NULL
chemistry$Time <- NULL
```

#####Remove duplicate rows
````{r}
##Remove duplicate rows
#Idenfies duplicates in a new data frame
duplicates <- chemistry[(duplicated(chemistry[c("StationID", "StationName", "Parameter", "DateTime")]) | duplicated(chemistry[c("StationID", "StationName", "Parameter", "DateTime")], fromLast = TRUE)), ]

#Removes duplicates from data
chemistry <- chemistry[!(duplicated(chemistry[c("StationID", "StationName", "Parameter", "DateTime")]) | duplicated(chemistry[c("StationID", "StationName", "Parameter", "DateTime")], fromLast = TRUE)), ]

#Average duplicates by Date/Time, Station ID, Parameter
duplicatesAveraged <- aggregate(Results ~ 
                                  StationID +
                                  StationName +
                                  Parameter +
                                  DateTime, 
                                duplicates, 
                                mean)

#Add averaged duplicates back in
chemistry <- rbind(chemistry, duplicatesAveraged)

#Remove unneeded variables
rm(duplicates, duplicatesAveraged)
```

#####Change to wide view
```{r}
if (!require('tidyr')) install.packages('tidyr', quiet=TRUE)
library(tidyr)

chemistry2 <- spread(chemistry, 
                     Parameter, 
                     Results, 
                     fill = NA)

describe(chemistry2)

rm(chemistry)
```

###Fish Counts
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/AllPineCreekFish.csv"

skip <- 0

fishCounts <- importGitHub(url, skip)
rm(url, skip)

describe(fishCounts)

#Fix DateTime Stamp from import
temp = t(as.data.frame(strsplit(as.character(fishCounts$Time),' ')))
rownames(temp)=NULL
fishCounts$Time <- temp
rm(temp)

fishCounts$Date <- as.Date(fishCounts$Date, format = "%m/%d/%Y")


fishCounts$DateTime <- as.POSIXct(paste(fishCounts$Date, fishCounts$Time), format = "%Y-%m-%d %H:%M")

#Convert fish names to all lowercase to avoid duplicates & some other data cleanup.
fishCounts$Fish <- tolower(fishCounts$Fish)
fishCounts$Fish <- gsub(" ", "_", fishCounts$Fish)
fishCounts$Fish <- gsub("\\(", "", fishCounts$Fish)
fishCounts$Fish <- gsub("\\)", "", fishCounts$Fish)
fishCounts$Fish <- factor(fishCounts$Fish)

#Convert counts to numeric
fishCounts$County <- as.numeric(fishCounts$County)

#Remove redundent variables
#fishCounts$Date <- NULL
fishCounts$Time <- NULL


#Drop unneeded variables dealing with how data was collected
fishCounts$Activity <- NULL
fishCounts$SRBC.Method <- NULL
fishCounts$Gear <- NULL

#Unstack
if (!require('tidyr')) install.packages('tidyr', quiet=TRUE)
library(tidyr)


fishCounts2 <- spread(fishCounts, 
                      Fish, 
                      County,
                      fill = 0)

fishCounts2 <- as.data.frame(fishCounts2)

summary(fishCounts2)
```

###Macro Counts
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/AllPineCreekMacros.csv"
skip = 0
macroCounts <- importGitHub(url, skip)
rm(url, skip)

#Fix DateTime Stamp from import
temp = t(as.data.frame(strsplit(as.character(macroCounts$Time),' ')))
rownames(temp)=NULL
macroCounts$Date <- as.Date(macroCounts$Date, 
                            format = "%m/%d/%Y")
macroCounts$Time <- temp
rm(temp)

macroCounts$DateTime <- as.POSIXct(paste(macroCounts$Date, macroCounts$Time), format = "%Y-%m-%d %H:%M")

#Convert fish names to all lowercase to avoid duplicates & some other data cleanup.
macroCounts$Macrostemum <- tolower(macroCounts$Macrostemum)
macroCounts$Activity <- NULL
macroCounts$SRBC.Method <- NULL
macroCounts$Gear <- NULL

#Remove redundent variables
macroCounts$Date <- NULL
macroCounts$Time <- NULL


#Unstack
macroCounts2 <- spread(macroCounts, 
                       Macrostemum, 
                       Count, 
                       fill = 0)
macroCounts2 <- as.data.frame(macroCounts2)
attach(macroCounts2)

summary(macroCounts2)

rm(macroCounts)
```

###Attribute data for each site
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/Pine_attributes.csv"

skip = 1

attributes <- importGitHub(url, skip)

rm(url, skip)

describe(attributes)
```

###Water Quality Measures for entire system
```{r}
url <- "https://raw.githubusercontent.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/master/Data/92_LittlePine_Cont.csv"

skip = 3
  
micro <- importGitHub(url, skip)

colnames(micro) <-  c("DateTime", 
                      "O2Dis", 
                      "pH", 
                      "SpCond", 
                      "Turbidity", 
                      "WaterTemp")

rm(url, skip)

#Clean Date/Time
temp = t(as.data.frame(strsplit(as.character(micro$DateTime),' ')))
rownames(temp)=NULL
micro$Date <- as.Date(temp[,1], 
                      format = "%m/%d/%Y")
micro$Time <- temp[,2]
rm(temp)

micro$DateTime <- as.POSIXct(paste(micro$Date, 
                                   micro$Time), 
                             format = "%Y-%m-%d %H:%M")

#Remove redundent variables
micro$Date <- NULL
micro$Time <- NULL

summary(micro)
```
