---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Steps

1. Clone the GitHub repo[^repo]
2. Close R Studio (if open)
3. Double click on this file
4. Run the below block

Local paths (`local`) only work when the working directory is set correctly.
The best way to accomplish this is to close R Studio and open the RMD by double click.
`setwd(...)` works too, but then you need to get all the contributors to agree on a particular repo location on their hard disks and that is like heading cats.
It _can_ be done in a corporate environment where the boss can mandate it, but when everyone is an equal, someone will get up in their feelings and wreck the whole thing.

BTW, I don't recommend uploading Excel files to GitHub.
It is _much_ better to convert them to CSV from Excel by hand then upload that.
GitHub has native support for CSV so they can be viewed on-line.
The issue at hand here is that `readxl` does not support url based refrences like `read.csv()` does, so it becomes a 3-step process.

1. Download file to a temp location
2. Read file from temp location
3. Delete temp file

```{r}
library(readxl)

file_name_remote <- 'https://github.com/HarrisburgUniversityPhd/SRBC-Signal2Noise/blob/master/Data/AllPineCreekChemistry.xlsx?raw=true'
destfile <- "myfile.xlsx"
download.file(file_name_remote, destfile, mode="wb")
data_remote <- read_excel(destfile)
file.remove(destfile)
head(data_remote)

file_name_local <- '../data/AllPineCreekChemistry.xlsx'
data_local <- read_excel(file_name_local)
head(data_local)
```

[^repo]: https://github.com/HarrisburgUniversityPhd/SRBC-Signal2Noise